### ISSUE TITLE
Bad build target ordering when module depends on ITK module

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/SlicerCustomAppTemplate#45]
## Summary

Observed an instance where initial build of a new custom app fails due to an ITK external module attempting to build before ITK.

## Steps to Reproduce

1. Use `cookiecutter` to create a new custom app
2. Add an external module that depends on some ITK external modules
3. Configure the project in CMake CLI
4. Build the project in Visual Studio 2022

## Expected Behavior

Project builds successfully. ITK external module targets depend on ITK target.

## Observed behavior

Build fails. ITK external modules are among the first build targets run, but since ITK has not been built yet they fail to find a suitable ITK.

**Comment by sjh26** [comment]
Which module is this? The solution may be a fix in the module's cmake, something like:

https://github.com/openigtlink/SlicerOpenIGTLink/commit/ca4b0fa5989403ee67a3e730f3df85f25e9a3bf4

In short, modules that have not bee used in a custom app before may not have the dependencies fully specified, since they are expecting that slicer has been fully built before they start.

**Comment by tbirdso** [comment]
Thanks @sjh26 , the module is SlicerHeart and @jcfr is looking into superbuild fixes there. 👍

**Comment by sjh26** [comment]
Yep, SlicerHeart ExternalModule files are missing the dependency info needed:
https://github.com/SlicerHeart/SlicerHeart/blob/1facd3d7cc58772c9ebbd5a9eb0b09c6cc2eb2a8/SuperBuild/External_ITKStrain.cmake#L6

**Comment by jcfr** [comment]
This should be fixed in https://github.com/SlicerHeart/SlicerHeart/pull/23

**Comment by jcfr** [comment]
Since this issue is independent of the SlicerCustomAppTemplate, I suggest we close it.
